"""Open / update the bot's pull request for the current run."""

from __future__ import annotations

import logging
from datetime import datetime, timezone

from github import Github, GithubException

from ..proposals.models import Proposal

log = logging.getLogger(__name__)


def open_pr(
    token: str,
    repo_slug: str,
    branch: str,
    base: str,
    proposals: list[Proposal],
) -> str | None:
    """Create a PR and return its URL. Returns None if no proposals or push failed."""
    if not proposals:
        return None

    gh = Github(token)
    repo = gh.get_repo(repo_slug)

    # If a previous bot PR is still open, skip — Section 9 (Governance) of the
    # design doc: don't pile up unreviewed PRs.
    open_bot_prs = [
        pr for pr in repo.get_pulls(state="open", base=base)
        if pr.head.ref.startswith("bot/auto-update")
    ]
    if open_bot_prs:
        existing = open_bot_prs[0]
        log.info(
            "skipping new PR — previous bot PR #%d (%s) is still open",
            existing.number, existing.html_url,
        )
        return existing.html_url

    title = _build_title(proposals)
    body = _build_body(proposals)

    try:
        pr = repo.create_pull(title=title, body=body, base=base, head=branch)
    except GithubException as e:
        log.error("PR creation failed: %s", e)
        return None

    log.info("opened PR #%d: %s", pr.number, pr.html_url)
    return pr.html_url


def _build_title(proposals: list[Proposal]) -> str:
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    n = len(proposals)
    high = sum(1 for p in proposals if p.confidence > 0.8)
    review = n - high
    return f"Auto-update {today}: {n} change{'s' if n != 1 else ''} ({high} high-confidence, {review} to review)"


def _build_body(proposals: list[Proposal]) -> str:
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        f"This PR was opened automatically by the updater bot at {ts}.",
        "",
        "## Summary",
        "",
        "| Change | File | Source | Confidence |",
        "|---|---|---|---|",
    ]
    for p in proposals:
        # First-line summary derived from commit message, falls back to reason.
        summary = (p.commit_message or p.reason).split(":", 1)[-1].strip()[:80]
        lines.append(
            f"| - [ ] {summary} | `{p.file_path}` | `{p.source_id}` | {p.confidence:.2f} |"
        )

    n = len(proposals)
    high = sum(1 for p in proposals if p.confidence > 0.8)
    medium = sum(1 for p in proposals if 0.5 <= p.confidence <= 0.8)
    lines += [
        "",
        f"**Total:** {n} change{'s' if n != 1 else ''} — {high} high-confidence "
        f"(>0.8), {medium} medium (0.5–0.8).",
        "",
        "## Per-change rationale",
        "",
    ]

    for p in proposals:
        lines.append(f"### `{p.file_path}`")
        lines.append("")
        lines.append(f"**Source:** {p.source_id}  ")
        lines.append(f"**Confidence:** {p.confidence:.2f}  ")
        lines.append(f"**Change type:** `{p.change_type}`  ")
        lines.append(f"**Reason:** {p.reason}")
        lines.append("")
        if p.raw_evidence:
            lines.append("<details><summary>Evidence</summary>")
            lines.append("")
            for k, v in p.raw_evidence.items():
                lines.append(f"- **{k}:** {v}")
            lines.append("")
            lines.append("</details>")
            lines.append("")

    lines += [
        "## How to review",
        "",
        "1. Read the diff for each change.",
        "2. High-confidence changes (>0.8) are usually safe to merge after a quick read.",
        "3. For lower-confidence changes, verify the linked evidence before merging.",
        "4. To drop a single change: revert that commit before merging.",
        "5. To reject the entire PR: close it. Items in this PR will be remembered "
        "and not re-proposed (see `state/manifest.json`).",
        "",
        "🤖 Generated by huji-ai-hub-bot",
    ]
    return "\n".join(lines)
